const $=s=>document.querySelector(s);
const S={data:null,all:[],rows:[],limit:25};
const pct=(n,d)=>n>0&&100*n/d<0.1?'<0.1':(100*n/d).toFixed(1);
const nf=new Intl.NumberFormat('en-GB');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nonempty=v=>typeof v==='string'&&v.trim().length>0;
function validDate(v){if(!nonempty(v))return false;const m=v.match(/^(\d{4})-(\d{2})-(\d{2})T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/);if(!m)return false;const [y,mo,d]=m.slice(1).map(Number);return mo>=1&&mo<=12&&d>=1&&d<=new Date(Date.UTC(y,mo,0)).getUTCDate()&&Number.isFinite(Date.parse(v));}
const date=v=>validDate(v)?new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}):'Not established';
const url=v=>{try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:'#';}catch{return '#';}};
const metricDefs=[['Project title',r=>r.titlePresent??(nonempty(r.title)&&r.title!=='Untitled project')],['Budget with currency',r=>typeof r.budget?.amount==='number'&&Number.isFinite(r.budget.amount)&&nonempty(r.budget.currency)],['Identified contracting process',r=>Array.isArray(r.processIds)?r.processIds.some(nonempty):r.contractingProcesses>0],['Project update date',r=>r.updatedValid??(validDate(r.updated)&&Date.parse(r.updated)<=Date.parse(S.data.generatedAt))],['Published sector',r=>Array.isArray(r.sector)&&r.sector.some(nonempty)]];
function bars(rows,compareRows=null,names=[]){return metricDefs.map(([label,predicate])=>{const one=(rs,name,secondary)=>{const n=rs.filter(predicate).length,d=rs.length;return `<div class="${secondary?'secondary':''}">${name?`<p class="series">${esc(name)}</p>`:''}<div class="bar-top"><span>${label}</span><strong>${d?`${nf.format(n)} / ${nf.format(d)} · ${pct(n,d)}%`:'No records'}</strong></div><div class="track" aria-hidden="true"><div class="fill" style="width:${d?100*n/d:0}%"></div></div></div>`};return `<div class="bar">${one(rows,names[0],false)}${compareRows?one(compareRows,names[1],true):''}</div>`}).join('');}
const sourceCaption=()=>`Calculated from ${nf.format(S.data.findings.licensedProjects)} licensed records in ${S.data.publishers.filter(p=>!p.excluded).length} available publisher packages. Analysis ${date(S.data.generatedAt)}; metric definitions ${S.data.metricVersion}.`;
function clock(label,value,note){return `<div class="clock"><span>${label}</span><strong>${esc(value)}</strong><p>${esc(note)}</p></div>`;}
async function init(){const q=new URLSearchParams(location.search),requested=q.get('snapshot');const safe=requested&&/^[a-zA-Z0-9_-]{1,100}$/.test(requested);if(requested&&!safe)throw new Error('The saved snapshot identifier is invalid. Open the Atlas without query parameters to choose the latest view.');const path=safe?`data/generated/snapshots/${requested}.json`:'data/generated/snapshot.json';const response=await fetch(path);if(!response.ok)throw new Error(requested?'The requested saved snapshot is unavailable. Remove the snapshot parameter to explicitly open the latest version.':'The saved analysis could not be loaded. Open the datastore sources or retry this page.');const data=await response.json();S.data=data;S.all=data.projects||[];S.loaded=new Set();S.path=path;
 document.querySelectorAll('.analysis-date').forEach(e=>e.textContent=date(data.generatedAt));$('#metric-version').textContent=data.metricVersion;$('#footer-snapshot').textContent=data.snapshotId;$('#snapshot-download').href=path;
 const included=data.publishers.filter(p=>!p.excluded),excluded=data.publishers.filter(p=>p.excluded);const age=Math.floor((Date.now()-Date.parse(data.generatedAt))/86400000);$('#notice').textContent=`Saved analysis ${date(data.generatedAt)}. ${included.length} of ${data.publishers.length} registry publishers included. ${excluded.map(p=>`${p.name}: ${p.excluded}`).join(' ')} ${age>7?`This analysis is ${age} days old. Check source dates before reuse.`:'A saved snapshot is not a live delivery report.'}`;
 const cr=data.publishers.find(p=>p.id==='costa_rica_cfia');if(cr){$('#hero-dates').textContent=`retrieved ${date(cr.loadedAt)}; package dated ${date(cr.publishedDate)}.`;$('#cr-source').href=url(cr.downloadUrl);$('#clock-proof').innerHTML=clock('Datastore retrieval',date(cr.loadedAt),'The latest valid file stored by the datastore.')+clock('Publisher’s package date',date(cr.publishedDate),'The publication timestamp declared inside that file.');}
 $('#story-bars').innerHTML=summaryBars(data.metricCounts,data.findings.licensedProjects);$('#story-population').innerHTML=esc(sourceCaption())+` <a href="${path}">Download source-linked calculations</a>.`;
 $('#publisher-windows').innerHTML=data.publishers.map(p=>`<article class="window"><h3>${esc(p.name)}</h3><p>${p.excluded?'Metadata only; no project content analysed.':`${nf.format(p.recordCount)} raw project records in this package.`}</p><p>Registry country context: ${esc(country(p.country))}. Coverage of all infrastructure is not established.</p><button data-publisher="${esc(p.id)}">Inspect this publisher</button></article>`).join('');$('#registry-caption').textContent=`Observed: ${data.publishers.length} publisher entries in the saved registry. This is not a country or asset count. ${sourceCaption()}`;
 for(const p of data.publishers){$('#publisher').add(new Option(p.name+(p.excluded?' (metadata only)':''),p.id));if(!p.excluded)$('#compare').add(new Option(p.name,p.id));}
 $('#publisher').value=included.find(p=>p.id==='costa_rica_cfia')?.id||included[0]?.id||data.publishers[0].id;
 const sectors=[...new Set(data.publishers.flatMap(p=>p.sectors||[]).filter(nonempty))].sort();sectors.forEach(s=>$('#sector').add(new Option(s,s)));[...new Set(data.publishers.flatMap(p=>p.statuses||[]).filter(nonempty))].sort().forEach(s=>$('#status').add(new Option(s,s)));
 readUrl();for(const id of ['publisher','sector','status','compare'])$('#'+id).addEventListener('change',()=>{S.limit=25;writeUrl();render();});
 $('#publisher-windows').addEventListener('click',e=>{const b=e.target.closest('[data-publisher]');if(!b)return;$('#publisher').value=b.dataset.publisher;$('#sector').value='';$('#status').value='';$('#compare').value='';S.limit=25;writeUrl();render();$('#explore').scrollIntoView();$('#publisher').focus({preventScroll:true});});
 $('#reset').onclick=()=>{$('#publisher').value=included.find(p=>p.id==='costa_rica_cfia')?.id||included[0].id;for(const k of ['sector','status','compare'])$('#'+k).value='';S.limit=25;writeUrl();render();};$('#more').onclick=()=>{S.limit+=25;renderRecords();};$('#export').onclick=exportCsv;$('#share').onclick=async()=>{writeUrl();try{await navigator.clipboard.writeText(location.href);$('#feedback').textContent='Link copied with this snapshot and all filters.';}catch{$('#feedback').textContent=`Copy this saved view: ${location.href}`;}};$('#print').onclick=()=>window.print();window.addEventListener('popstate',()=>{readUrl();S.limit=25;render();});
 $('#readiness').innerHTML=`<p>${esc(sourceCaption())} The following source dates and fingerprints identify what was analysed. Excluded publishers remain visible; their missing analysis is not a zero.</p>`+data.publishers.map(p=>`<details><summary>${esc(p.name)}: ${p.excluded?'excluded':nf.format(p.recordCount)+' records'}</summary><p>${esc(p.excluded||'Included under the stated open licence.')}</p><p>Licence: <a href="${url(p.license?.url)}">${esc(p.license?.title_short||'Not stated')}</a>. Retrieved ${date(p.loadedAt)}; package dated ${date(p.publishedDate)}. Version ${esc(p.packageVersion||'not established')}. Repeated project IDs: ${p.excluded?'not assessed':nf.format(p.duplicateIds||0)}.</p><p><a href="${url(p.downloadUrl)}">Source JSON</a> · <a href="${url(p.portal?.url)}">Publisher portal</a></p><code class="raw">${esc(p.sha256||'No content fingerprint: excluded')}</code></details>`).join('');render();
}
function country(c){try{return new Intl.DisplayNames(['en'],{type:'region'}).of(String(c).toUpperCase());}catch{return c||'Not specified';}}
function readUrl(){const q=new URLSearchParams(location.search);for(const k of ['publisher','sector','status','compare']){const value=q.get(k);if(value!==null&&[...$('#'+k).options].some(o=>o.value===value))$('#'+k).value=value;}}
function writeUrl(){const q=new URLSearchParams({snapshot:S.data.snapshotId});for(const k of ['publisher','sector','status','compare'])if($('#'+k).value)q.set(k,$('#'+k).value);history.replaceState(null,'',`${location.pathname}?${q}#explore`);}
function filtered(id){return S.all.filter(r=>r.sourceId===id&&(!$('#sector').value||r.sector.includes($('#sector').value))&&(!$('#status').value||r.status===$('#status').value));}
async function render(){const turn=(S.turn||0)+1;S.turn=turn;const wanted=[$('#publisher').value,$('#compare').value].filter(Boolean);$('#feedback').textContent='Loading the selected publisher records…';$('#export').disabled=true;$('#bars').innerHTML='<p>Loading the selected publication profile…</p>';$('#projects').innerHTML='';$('#project-count').textContent='Loading records…';$('#more').hidden=true;S.rows=[];try{await Promise.all(wanted.map(loadRecords));}catch(e){if(turn===S.turn)$('#feedback').textContent=e.message;return;}if(turn!==S.turn)return;$('#feedback').textContent='';const p=S.data.publishers.find(p=>p.id===$('#publisher').value);if(!p)return;S.rows=filtered(p.id);const cp=S.data.publishers.find(p=>p.id===$('#compare').value);$('#name').textContent=p.name;$('#scope').textContent=p.excluded?`Registry metadata only. ${p.excluded}`:`${nf.format(p.recordCount)} raw records in this source package; ${nf.format(S.rows.length)} match the filters. ${country(p.country)} is the registry country context, not a national coverage estimate.`;$('#source').href=url(p.downloadUrl);$('#comparison').textContent=p.excluded?'No profile calculated for this source. No records is different from zero publication.':cp?`Descriptive comparison only: ${p.name} and ${cp.name}. The same sector and stage filters apply to both. Institutional remits, selection and update practices can differ. These percentages do not rank performance; no national population denominator is known.`:'All percentages use the selected publisher and current filters. These measures show field availability, not substantive accuracy or an official transparency score.';$('#bars').innerHTML=p.excluded?'<p class="empty">A publication profile is unavailable for this source.</p>':bars(S.rows,cp?filtered(cp.id):null,cp?[p.name,cp.name]:[]);
 $('#publisher-clocks').innerHTML=clock('Latest stored retrieval',date(p.loadedAt),'Datastore timestamp, not a freshness verdict.')+clock('Package publication',date(p.publishedDate),'Publisher-declared date, separate from project updates.');$('#provenance').innerHTML=`<p>Analysis ${date(S.data.generatedAt)}. Source schema version ${esc(p.packageVersion||'not established')}. Repeated non-empty IDs: ${p.excluded?'not assessed':nf.format(p.duplicateIds||0)}. Rows are retained.</p><p><a href="${url(p.portal?.url)}">Publisher portal</a> · <a href="${url(p.license?.url)}">${esc(p.license?.title_short||'Licence not stated')}</a> · <a href="#method">Metric dictionary</a></p><p>SHA-256 of source bytes:</p><code class="raw">${esc(p.sha256||'Not available')}</code>`;$('#export').disabled=!S.rows.length;renderRecords();}
function renderRecords(){$('#project-count').textContent=`Showing ${nf.format(Math.min(S.limit,S.rows.length))} of ${nf.format(S.rows.length)} matching records`;$('#projects').innerHTML=S.rows.slice(0,S.limit).map((r,i)=>`<details><summary>${esc(r.title||'Title not published')}<div class="record-meta">${esc(r.status||'Stage not published')} · ${esc(r.id||'Identifier not published')}</div></summary><dl class="record-detail"><div><dt>Published sector codes</dt><dd>${esc(r.sector.join(', ')||'Not published')}</dd></div><div><dt>Project updated (as published)</dt><dd>${esc(r.updated||'Not published')}${r.updated&&!metricDefs[3][1](r)?' · invalid or later than the analysis date':''}</dd></div><div><dt>Budget, separate from contract value</dt><dd>${metricDefs[1][1](r)?`${esc(r.budget.currency)} ${nf.format(r.budget.amount)}`:'Amount and currency not both established'}</dd></div><div><dt>Identified contracting processes</dt><dd>${nf.format(r.contractingProcesses||0)} entries; IDs: ${esc(r.processIds?.join(', ')||'Not published')}</dd></div></dl><p class="source-note">Snapshot ${esc(S.data.snapshotId)} · source project ID <code>${esc(r.id)}</code>. <a href="${url(r.source)}">Open original JSON package</a> and locate this ID. Repeated IDs, if present, may identify more than one row. These fields are transformed extracts, not an independent verification of the project.</p></details>`).join('')||'<p class="empty">No records match. Change the filters or select another publisher.</p>';$('#more').hidden=S.limit>=S.rows.length;}
function csvCell(v){let s=String(v??'');if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
function exportCsv(){const keys=['snapshot','publisher','id','title','status','sector','updated','budgetAmount','budgetCurrency','identifiedProcesses','processIds','source'];const lines=S.rows.map(r=>[S.data.snapshotId,r.publisher,r.id,r.title,r.status,r.sector.join('|'),r.updated,r.budget?.amount,r.budget?.currency,r.contractingProcesses,r.processIds?.join('|'),r.source].map(csvCell).join(','));const blob=new Blob(['\uFEFF'+keys.join(',')+'\n'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const object=URL.createObjectURL(blob),a=document.createElement('a');a.href=object;a.download=`atlas-${$('#publisher').value}-${S.data.snapshotId}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(object),1000);$('#feedback').textContent=`Exported ${nf.format(S.rows.length)} filtered records with source links and snapshot identity.`;}
init().catch(e=>{$('#notice').textContent=e.message;$('#name').textContent='Saved analysis unavailable';$('#feedback').textContent='Use the source links or reload to try again.';});

function summaryBars(values,d){return metricDefs.map(([label],i)=>{const n=values[i];return `<div class="bar"><div class="bar-top"><span>${label}</span><strong>${nf.format(n)} / ${nf.format(d)} · ${pct(n,d)}%</strong></div><div class="track" aria-hidden="true"><div class="fill" style="width:${100*n/d}%"></div></div></div>`}).join('');}
async function loadRecords(id){if(S.loaded.has(id))return;const p=S.data.publishers.find(p=>p.id===id);if(!p||p.excluded){S.loaded.add(id);return;}if(!S.data.recordFiles){S.loaded.add(id);return;}S.pending??=new Map();if(S.pending.has(id))return S.pending.get(id);const task=(async()=>{const response=await fetch(S.data.recordFiles[id]);if(!response.ok)throw Error('This publisher’s records could not be loaded. Retry the selection or open its original source.');const rows=await response.json();S.all.push(...rows.map(r=>({...r,sourceId:id,publisher:p.name,country:p.country,source:p.downloadUrl})));S.loaded.add(id);})();S.pending.set(id,task);try{await task;}finally{S.pending.delete(id);}}
