import {createGlyph} from './glyph.mjs';
const $=id=>document.getElementById(id), q=new URLSearchParams(location.search);
const aliases={costa_rica_cfia:'Costa Rica · CFIA',indonesia_cost_west_lombok:'West Lombok',indonesia_cost_ntb:'NTB · Indonesia',malawi_cost_malawi:'Malawi · CIRA',nigeria_kaduna:'Kaduna · KADPPA',uganda_gpp:'Uganda · PPDA',zambia_ncc:'Zambia · NCC',mozambique_ane:'Mozambique · Road Fund',mexico_cost_jalisco:'Jalisco · Mexico',ghana_cost_sekondi_takoradi:'Sekondi Takoradi · Ghana',ecuador_cost_ecuador:'Ecuador'};
const definitions=[
 {id:'title',label:'Project title',short:'Title',path:'title',question:'Can someone identify the project?',meaning:'A non-empty title helps a reader recognize what a record describes. It does not establish that the description is accurate.'},
 {id:'budget',label:'Budget with currency',short:'Budget',path:'budget.amount.amount + budget.amount.currency',question:'Can someone interpret the published budget?',meaning:'A numeric amount and its currency are both present. Zero is a published amount. This is a budget, not a contract value, expenditure or verified investment total.'},
 {id:'process',label:'Identified contracting process',short:'Process link',path:'contractingProcesses[].id',question:'Can someone follow the procurement trail?',meaning:'At least one contracting process has a non-empty identifier. An identifier alone does not prove that the linked procurement record is accessible or complete.'},
 {id:'updated',label:'Valid project update date',short:'Update date',path:'updated',question:'Is there a usable update timestamp?',meaning:'The record has a valid calendar timestamp no later than the saved analysis. Presence is different from recency: this measure does not say the project is up to date.'},
 {id:'sector',label:'Published sector',short:'Sector',path:'sector[]',question:'Can someone place the project in a sector?',meaning:'At least one non-empty sector code is present. This checks presence, not the correctness or comparability of the classification.'}
];
const S={data:null,pubs:[],selected:q.get('publisher')||'costa_rica_cfia',compare:q.get('compare')||'',map:null,markers:{},story:'availability',field:null,records:new Map()};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const alias=p=>aliases[p.id]||p.name, current=()=>S.pubs.find(p=>p.id===S.selected), compared=()=>S.pubs.find(p=>p.id===S.compare);
const date=v=>v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}):'Not established';
const safeUrl=v=>{try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}};
const number=n=>new Intl.NumberFormat('en-GB').format(n), percentage=(n,d)=>!d?'Unavailable':n>0&&n/d*100<.1?'<0.1%':(n/d*100).toFixed(1)+'%';
const descriptor=p=>p?{id:p.id,label:alias(p),available:p.available&&!p.excluded,recordCount:p.recordCount,axes:definitions.map((d,i)=>({id:d.id,label:d.short,count:p.metricCounts?.[i]??null,total:p.recordCount}))}:null;
const glyph=createGlyph($('glyph'),{onInspect:({axisId})=>inspect(axisId)});
function evidenceLink(){const params=new URLSearchParams({snapshot:S.data.snapshotId,publisher:S.selected});for(const key of ['sector','status'])if(q.get(key))params.set(key,q.get(key));if(S.compare)params.set('compare',S.compare);return `evidence.html?${params}#explore`}
function sourceLinks(){return `<p class="source-boundary"><a href="${evidenceLink()}">Open publisher records and filters ↗</a><br><a href="${safeUrl(current().downloadUrl)}">Original publisher JSON ↗</a><br>Analysis ${date(S.data.generatedAt)} · <a href="data/generated/snapshots/${S.data.snapshotId}.json">Saved calculations</a></p>`}
function writeUrl(){if(!S.data)return;const params=new URLSearchParams({snapshot:S.data.snapshotId,publisher:S.selected,story:S.story});if(S.compare)params.set('compare',S.compare);if(S.field)params.set('field',S.field);for(const k of ['sector','status'])if(q.get(k))params.set(k,q.get(k));const c=S.map?.getCenter(),z=S.map?.getZoom();if(c&&Number.isFinite(c.lat)&&Number.isFinite(c.lng)){params.set('lat',Math.max(-80,Math.min(80,c.lat)).toFixed(4));params.set('lng',(((c.lng+180)%360+360)%360-180).toFixed(4));params.set('zoom',z)}history.replaceState(null,'',`${location.pathname}?${params}`)}
function render(){const p=current(),cp=compared();$('publisher-name').textContent=alias(p);$('publisher-name').title=p.name;$('scope').textContent=p.excluded?'Metadata only · project content excluded':'One publisher’s records. Geographic context is not national coverage.';$('record-count').textContent=p.excluded?'n/a':number(p.recordCount);$('hub-unit').textContent=p.excluded?'no profile':'records';$('primary-label').textContent=alias(p);$('compare-label').textContent=cp?alias(cp)+(cp.excluded?' (unavailable)':''):'';$('compare-legend').hidden=!cp;$('publisher-select').value=p.id;$('compare-picker').value=cp?.id||'';glyph.update(descriptor(p),descriptor(cp));Object.entries(S.markers).forEach(([id,m])=>m.getElement()?.classList.toggle('selected',id===p.id));document.title=`${alias(p)} · Infrastructure in view`;if($('inspector').open)renderInspector();writeUrl()}
function select(id,moveMap=true){if(!S.pubs.some(p=>p.id===id))return;S.selected=id;render();if(moveMap&&S.markers[id])S.map.panTo(S.markers[id].getLatLng(),{animate:!matchMedia('(prefers-reduced-motion: reduce)').matches,duration:.55});}
function openInspector(story,field=null){S.story=story;S.field=field;renderInspector();if(!$('inspector').open)$('inspector').showModal();writeUrl()}
function inspect(axisId){if(definitions.some(d=>d.id===axisId))openInspector('field',axisId)}
function renderInspector(){const p=current(),cp=compared();$('detail-kicker').textContent=alias(p);let title='',html='';
 if(S.story==='field'){const i=definitions.findIndex(d=>d.id===S.field),d=definitions[i];title=d.question;html=p.excluded?'<p>This publisher’s project content is excluded because no reuse licence was stated. No field ratio is calculated.</p>':`<p class="big">${percentage(p.metricCounts[i],p.recordCount)}</p><p>${number(p.metricCounts[i])} of ${number(p.recordCount)} records have <strong>${d.label.toLowerCase()}</strong>.</p>${cp?`<p>${esc(alias(cp))}: ${cp.excluded?'profile unavailable':number(cp.metricCounts[i])+' / '+number(cp.recordCount)+' ('+percentage(cp.metricCounts[i],cp.recordCount)+')'}.</p>`:''}<p>${d.meaning}</p><dl><dt>Source field</dt><dd>${esc(d.path)}</dd><dt>Denominator</dt><dd>All raw records in this publisher’s saved package. Repeated IDs remain in the population.</dd></dl>`;}
 else if(S.story==='freshness'){title='Two clocks. Two different claims.';html=`<p>Published by the source</p><p class="date">${date(p.publishedDate)}</p><p>Retrieved by the datastore</p><p class="date">${date(p.loadedAt)}</p><p>A recent retrieval can contain an older publication. Neither date establishes current project delivery. The datastore can retain its latest valid package after a failed refresh.</p>`;}
 else if(S.story==='records'){title='Follow a record.';html=p.excluded?'<p>No project content is redistributed for this publisher.</p>':'<p id="record-preview">Loading three titles from the saved source…</p>';}
 else {title='What becomes visible?';html=`<p>Each arm measures one kind of information published in infrastructure project records. The outer tick means 100%; every arm begins at zero at the inner ring. Each of the 20 engraved slots spans five percentage points, not five records. The five measures stay separate. There is no combined score.</p><p>Choose a publisher to see its profile change. Select an arm to inspect what it measures. A comparison draws both publishers on the same five scales, with separate record populations.</p><p>Animation moves between two selected profiles. It is not a historical trend or a series of intermediate observations.</p><p>Country outlines and publisher anchors provide geographic context only. They do not locate projects or establish national coverage.</p><p>Snapshot ${esc(S.data.snapshotId)} · ${date(S.data.generatedAt)}. ${Math.floor((Date.now()-Date.parse(S.data.generatedAt))/86400000)>7?'This saved analysis is over seven days old; check source dates before reuse.':''}</p><p><a href="data/map/README.md">Map provenance</a> · <a href="evidence.html#method">Full metric dictionary</a></p>`;}
 $('detail-title').textContent=title;$('detail-content').innerHTML=html+sourceLinks();if(S.story==='records'&&!p.excluded)loadRecords(p);
}
async function loadRecords(p){try{if(!S.records.has(p.id))S.records.set(p.id,fetch(S.data.recordFiles[p.id]).then(r=>{if(!r.ok)throw Error('Unavailable');return r.json()}));const rows=await S.records.get(p.id);if(S.story==='records'&&S.selected===p.id&&$('record-preview'))$('record-preview').outerHTML='<ol>'+rows.slice(0,3).map(r=>`<li><p>${esc(r.title||'Title not published')}<br><small>${esc(r.id||'Identifier not published')}</small></p></li>`).join('')+'</ol>';}catch{S.records.delete(p.id);if($('record-preview'))$('record-preview').textContent='These records could not be loaded. Open the original source below or retry Records.'}}
function world(){S.map.fitBounds([[-55,-180],[75,180]]);}
function wireDrag(){const el=$('instrument'),handle=$('move');let drag=null;function shift(dx,dy){const r=el.getBoundingClientRect();const x=+(el.dataset.x||0),y=+(el.dataset.y||0);el.dataset.x=x+Math.max(-r.left+8,Math.min(innerWidth-r.right-8,dx));el.dataset.y=y+Math.max(65-r.top,Math.min(innerHeight-r.bottom-80,dy));el.style.translate=`${el.dataset.x}px ${el.dataset.y}px`;}function reset(){el.style.translate='';el.dataset.x=el.dataset.y='0'}handle.addEventListener('pointerdown',e=>{e.preventDefault();handle.setPointerCapture(e.pointerId);drag=[e.clientX,e.clientY]});handle.addEventListener('pointermove',e=>{if(drag){shift(e.clientX-drag[0],e.clientY-drag[1]);drag=[e.clientX,e.clientY]}});for(const type of ['pointerup','pointercancel','lostpointercapture'])handle.addEventListener(type,()=>drag=null);handle.addEventListener('keydown',e=>{const delta={ArrowLeft:[-10,0],ArrowRight:[10,0],ArrowUp:[0,-10],ArrowDown:[0,10]}[e.key];if(delta){e.preventDefault();shift(...delta)}if(e.key==='Home'){e.preventDefault();reset()}});$('reset').onclick=reset;window.addEventListener('resize',reset);}
async function boot(){try{const snap=q.get('snapshot');if(snap&&!/^[A-Za-z0-9_-]{1,100}$/.test(snap))throw Error('Invalid snapshot link.');const r=await fetch(snap?`data/generated/snapshots/${snap}.json`:'data/generated/snapshot.json');if(!r.ok)throw Error('This saved snapshot is unavailable.');S.data=await r.json();if(snap&&S.data.snapshotId!==snap)throw Error('Snapshot identity mismatch.');S.pubs=S.data.publishers;if(!current())S.selected=S.pubs.find(p=>!p.excluded).id;if(!compared())S.compare='';
 const [anchors,geo]=await Promise.all([fetch('data/map/publisher-anchors.json').then(r=>r.json()),fetch('data/map/world.geojson').then(r=>r.ok?r.json():null).catch(()=>null)]);S.map=L.map('map',{zoomControl:false,minZoom:.5,maxZoom:7,zoomSnap:.25}).setView([12,0],innerWidth<=720?1:2);S.map.attributionControl.addAttribution('Natural Earth · public domain');L.control.zoom({position:'bottomright'}).addTo(S.map);if(geo)L.geoJSON(geo,{style:{color:'#bdc9c3',weight:.65,fillColor:'#dce4dc',fillOpacity:.7}}).addTo(S.map);else $('status').textContent='Country outlines unavailable; publisher selection remains available.';
 S.pubs.forEach(p=>{const a=anchors[p.id];if(!a)return;const m=L.marker(a,{title:p.name,alt:p.name+' publisher anchor',icon:L.divIcon({className:'publisher-icon'+(p.excluded?' metadata':''),html:'<span></span>',iconSize:[44,44],iconAnchor:[22,22]})}).addTo(S.map).bindTooltip(alias(p));m.on('click',()=>select(p.id,false));S.markers[p.id]=m});
 if(q.has('lat')&&q.has('lng')&&Number.isFinite(+q.get('lat'))&&Number.isFinite(+q.get('lng'))&&Math.abs(+q.get('lat'))<=80&&Math.abs(+q.get('lng'))<=180){const zoom=+q.get('zoom');S.map.setView([+q.get('lat'),+q.get('lng')],Number.isFinite(zoom)&&zoom>=.5&&zoom<=7?zoom:2)}S.map.on('moveend',writeUrl);
 $('publisher-select').innerHTML=S.pubs.map(p=>`<option value="${esc(p.id)}">${esc(alias(p))}</option>`).join('');$('compare-picker').innerHTML='<option value="">No comparison</option>'+S.pubs.map(p=>`<option value="${esc(p.id)}">${esc(alias(p))}</option>`).join('');$('publisher-select').onchange=e=>select(e.target.value);$('compare-picker').onchange=e=>{S.compare=e.target.value;render()};for(const [id,step]of [['previous',-1],['next',1]])$(id).onclick=()=>select(S.pubs[(S.pubs.findIndex(p=>p.id===S.selected)+step+S.pubs.length)%S.pubs.length].id);
 $('methods').onclick=()=>openInspector('methods');$('dates').onclick=()=>openInspector('freshness');$('records').onclick=()=>openInspector('records');$('close').onclick=()=>$('inspector').close();$('inspector').addEventListener('close',()=>{S.story='availability';S.field=null;writeUrl()});$('world').onclick=world;wireDrag();$('share').onclick=async()=>{writeUrl();try{await navigator.clipboard.writeText(location.href);$('status').textContent='Link copied with the saved snapshot and current selection.'}catch{$('status').textContent='Copy this view from the address bar.'}};render();const story=q.get('story');if(story==='field'&&definitions.some(d=>d.id===q.get('field')))inspect(q.get('field'));else if(['methods','freshness','records'].includes(story))openInspector(story);
 }catch(e){$('publisher-name').textContent='Evidence unavailable';$('scope').textContent=e.message;$('status').innerHTML='<a href="evidence.html">Open the evidence and source links</a>';}}
window.addEventListener('popstate',()=>location.reload());boot();
