import {resolveLens} from './map-selection.mjs';
const $=id=>document.getElementById(id), q=new URLSearchParams(location.search);
const aliases={costa_rica_cfia:'Costa Rica · CFIA',indonesia_cost_west_lombok:'West Lombok',indonesia_cost_ntb:'NTB · Indonesia',malawi_cost_malawi:'Malawi · CIRA',nigeria_kaduna:'Kaduna · KADPPA',uganda_gpp:'Uganda · PPDA',zambia_ncc:'Zambia · NCC',mozambique_ane:'Mozambique · Road Fund',mexico_cost_jalisco:'Jalisco · Mexico',ghana_cost_sekondi_takoradi:'Sekondi Takoradi · Ghana',ecuador_cost_ecuador:'Ecuador'};
const definitions=[
 {id:'projects',label:'Published projects',question:'How many projects are represented?'},
 {id:'budget',label:'Published budget',question:'What money is reported for these projects?'},
 {id:'sectors',label:'Infrastructure mix',question:'What kinds of infrastructure are represented?'},
 {id:'stages',label:'Reported stage',question:'What stage does the publisher report?'},
 {id:'procurement',label:'Procurement',question:'How is procurement described?'}
];
const labels={education:'Education',health:'Health','health sector':'Health sector (source label)',waterAndWaste:'Water & waste',transport:'Transport','transport.road':'Roads','transport.urban':'Urban transport','transport.water':'Water transport',governance:'Government facilities',economy:'Economic infrastructure',energy:'Energy',socialHousing:'Housing',cultureSportsAndRecreation:'Sport & recreation',communications:'Communications',naturalResources:'Natural resources',completion:'Completion',implementation:'Implementation',identification:'Identification',preparation:'Preparation',maintenance:'Maintenance',decommissioning:'Decommissioning',cancelled:'Cancelled',open:'Open procedure',selective:'Selective procedure',limited:'Limited procedure',direct:'Direct procedure',Unstated:'Not stated'};
const label=v=>labels[v]||v;
const S={data:null,pubs:[],selected:q.get('publisher')||'costa_rica_cfia',map:null,markers:{},story:'availability',field:null,records:new Map()};
let lensMap, lensFrame=0, lensWrite=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const alias=p=>aliases[p.id]||p.name, current=()=>S.pubs.find(p=>p.id===S.selected);
const date=v=>v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}):'Not established';
const safeUrl=v=>{try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}};
const number=n=>new Intl.NumberFormat('en-GB').format(n), percentage=(n,d)=>!d?'Unavailable':n>0&&n/d*100<.1?'<0.1%':(n/d*100).toFixed(1)+'%';
const compact=n=>new Intl.NumberFormat('en-GB',{notation:'compact',maximumFractionDigits:1}).format(n);
function insightViews(p){const x=p.insights;if(!x?.available)return [];const n=x.population.records,b=x.budgets.byCurrency,mainBudget=[...b].sort((a,b)=>b.records-a.records)[0],sector=x.sectors.top,stage=x.stages.top,unit=n===x.population.distinctIds?'projects':'records';const methods=Object.entries(p.procurement?.methods||{}).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])),method=methods[0],total=p.procurement?.processEntries||0;
 return [
 {value:number(x.population.distinctIds),note:'projects published',detail:'in this publication'},
 {value:mainBudget?`${mainBudget.currency} ${compact(mainBudget.amount)}`:'Not published',note:mainBudget?`${number(mainBudget.records)} of ${number(n)} ${unit}`:'no numeric project budgets',detail:b.length>1?`${b.length-1} other ${b.length===2?'currency':'currencies'}; open totals`:mainBudget?'reported project budgets':''},
 {share:sector&&n?sector.records/n:null,value:sector?label(sector.value):'Not stated',note:sector?`${number(sector.records)} of ${number(n)} ${unit}`:'no sector labels',detail:sector?'largest reported sector':''},
 {share:stage&&n?Math.max(stage.records,x.stages.unstatedRecords)/n:null,value:!stage||x.stages.unstatedRecords>stage.records?'Not stated':label(stage.value),note:!stage||x.stages.unstatedRecords>stage.records?`${number(x.stages.unstatedRecords)} of ${number(n)} ${unit}`:`${number(stage.records)} of ${number(n)} ${unit}`,detail:'publisher-reported stage'},
 {share:method&&total?method[1]/total:null,value:method&&method[0]!=='Unstated'?label(method[0]):'Not stated',note:method?`${number(method[1])} of ${number(total)} processes`:'no procurement method',detail:method&&method[0]!=='Unstated'?'most reported procedure':''}
 ];}
function drawInsights(p){const host=$('glyph');host.setAttribute('aria-label',p?`${alias(p)} infrastructure portrait`:'No publisher selected');if(!p?.insights?.available){host.innerHTML=p?'<p class="portrait-unavailable">Metadata only; project content excluded.</p>':'';return;}
 const views=insightViews(p);host.innerHTML='<svg viewBox="0 0 100 100" aria-hidden="true" class="portrait-links"><path d="M50 39V12M60 45L81 35M57 59L73 81M43 59L27 81M40 45L19 35"/></svg>'+views.map((v,i)=>`<button class="insight-prong prong-${i}" data-insight="${definitions[i].id}" aria-label="${esc(definitions[i].question+' '+v.value+'. '+v.note)}"><span class="prong-title">${definitions[i].label}</span><strong>${esc(v.value)}</strong><span>${esc(v.note)}</span><small>${esc(v.detail)}</small>${v.share!=null?`<i class="prong-share" aria-hidden="true"><i style="width:${Math.max(0,Math.min(100,v.share*100))}%"></i></i>`:''}</button>`).join('');host.querySelectorAll('[data-insight]').forEach(el=>el.onclick=()=>inspect(el.dataset.insight));}
function evidenceLink(){const params=new URLSearchParams({snapshot:S.data.snapshotId,publisher:S.selected});for(const key of ['sector','status'])if(q.get(key))params.set(key,q.get(key));return `evidence.html?${params}#explore`}
function sourceLinks(){return `<p class="source-boundary"><a href="${evidenceLink()}">Open publisher records and filters ↗</a><br><a href="${safeUrl(current().downloadUrl)}">Original publisher JSON ↗</a><br>Analysis ${date(S.data.generatedAt)} · <a href="data/generated/snapshots/${S.data.snapshotId}.json">Saved calculations</a></p>`}
function writeUrl(){if(!S.data)return;const params=new URLSearchParams({snapshot:S.data.snapshotId,publisher:S.selected||'',story:S.story});if(S.field)params.set('field',S.field);for(const k of ['sector','status'])if(q.get(k))params.set(k,q.get(k));const c=S.map?.getCenter(),z=S.map?.getZoom();if(c&&Number.isFinite(c.lat)&&Number.isFinite(c.lng)){params.set('lat',Math.max(-80,Math.min(80,c.lat)).toFixed(4));params.set('lng',(((c.lng+180)%360+360)%360-180).toFixed(4));params.set('zoom',z)}const h=$('move').getBoundingClientRect();params.set('lensX',((h.left+h.width/2)/innerWidth).toFixed(5));params.set('lensY',((h.top+h.height/2)/innerHeight).toFixed(5));const focus=S.map.containerPointToLatLng(lensPoint());params.set('focusLat',focus.lat.toFixed(5));params.set('focusLng',focus.lng.toFixed(5));history.replaceState(null,'',`${location.pathname}?${params}`)}
function render(write=true){const p=current();
 for(const id of ['methods','dates','records'])$(id).disabled=!p;
 if(!p){$('publisher-name').textContent='No publisher in the lens';$('publisher-name').title='';$('scope').textContent='Move the lens or map towards a publisher dot. Anchors do not locate projects.';$('record-count').textContent='';$('hub-unit').textContent='No profile here';$('primary-label').textContent='Move the lens to a publisher';$('publisher-select').value='';drawInsights(null);Object.values(S.markers).forEach(m=>m.getElement()?.classList.remove('selected'));document.title='Explore the map · Infrastructure in view';if($('inspector').open)$('inspector').close();if(write)writeUrl();return;}
$('publisher-name').textContent=alias(p);$('publisher-name').title=p.name;$('scope').textContent=p.excluded?'Metadata only · project content excluded':(q.has('sector')||q.has('status')?'Profile: all publisher records. Sector/status filters apply only in the record explorer.':`Published ${date(p.publishedDate)}. This publisher's records, not national coverage.`);$('record-count').textContent='';$('hub-unit').textContent='';$('primary-label').textContent=alias(p);$('publisher-select').value=p.id;drawInsights(p);Object.entries(S.markers).forEach(([id,m])=>m.getElement()?.classList.toggle('selected',id===p.id));document.title=`${alias(p)} · Infrastructure in view`;if($('inspector').open)renderInspector();if(write)writeUrl()}
function lensPoint(){const h=$('move').getBoundingClientRect(),r=$('map').getBoundingClientRect();return L.point(h.left+h.width/2-r.left,h.top+h.height/2-r.top)}
function refreshLens(write=false){if(!lensMap)return;const focus=S.map.containerPointToLatLng(lensPoint());lensMap.setView(focus,S.map.getZoom()+1,{animate:false});const size=lensMap.getSize(),center=size.divideBy(2);const candidates=Object.entries(S.markers).map(([id,m])=>({id,point:lensMap.latLngToContainerPoint(m.getLatLng())}));const hit=resolveLens(center,candidates,Math.min(size.x,size.y)/2-5);const id=hit?.id||null;$('lens-map').dataset.focus=`${focus.lat.toFixed(4)},${focus.lng.toFixed(4)}`;if(id!==S.selected){S.selected=id;render(false)}if(write)writeUrl()}
function queueLens(write=false){lensWrite ||= write;if(lensFrame)return;lensFrame=requestAnimationFrame(()=>{lensFrame=0;const save=lensWrite;lensWrite=false;refreshLens(save)})}
function panFocus(target){const offset=lensPoint().subtract(S.map.getSize().divideBy(2));S.map.panTo(S.map.unproject(S.map.project(target).subtract(offset)),{animate:false})}
function select(id){if(!S.markers[id])return;panFocus(S.markers[id].getLatLng());refreshLens(true)}
function openInspector(story,field=null){if(!current())return;S.story=story==='freshness'?'investment':story;S.field=field;renderInspector();if(!$('inspector').open)$('inspector').showModal();writeUrl()}
function inspect(axisId){if(definitions.some(d=>d.id===axisId))openInspector('field',axisId)}
function investmentView(p){const x=p?.insights;if(!x?.available)return {title:'Investment overview unavailable',html:'<p>Project content is unavailable for this publisher, so no investment overview is calculated.</p>'};const n=x.population.records,projects=x.population.distinctIds,b=x.budgets.byCurrency,rows=b.map(v=>`<tr><td>${esc(v.currency)}</td><td>${number(v.amount)}</td><td>${number(v.records)}</td></tr>`).join('');const subject=x.population.missingProjectIds?`${number(n)} published records`:`${number(projects)} published ${projects===1?'project':'projects'}`;const title=!b.length?`${subject}. Their budgets are still out of view.`:`Follow the money behind ${subject}.`;const html=`<p>Budgets are published for ${number(x.budgets.usableRecords)} of ${number(n)} records.${x.budgets.missingRecords?` ${number(x.budgets.missingRecords)} have no usable amount and currency.`:``}</p>${b.length?`<table class="inspect-table"><thead><tr><th>Currency</th><th>Reported budget</th><th>Records</th></tr></thead><tbody>${rows}</tbody></table>`:'<p>No numeric project budgets with currencies are published.</p>'}<p>Reported project budgets; currencies are kept separate. These totals do not measure expenditure or completed works.</p><details><summary>Source dates</summary><p>Published ${date(p.publishedDate)} · retrieved ${date(p.loadedAt)} · analysis ${date(S.data.generatedAt)}</p></details>`;return {title,html};}
function renderInspector(){const p=current();$('detail-kicker').textContent=alias(p);let title='',html='';
 if(S.story==='field'){const d=definitions.find(d=>d.id===S.field),x=p.insights;title=d.question;const n=x?.population.records||0;if(!x?.available){html='<p>Project content is excluded for this publisher.</p>';}else if(S.field==='projects'){html=`<p class="big">${number(x.population.distinctIds)}</p><p>Distinct published project IDs in ${number(n)} source records. These are the projects represented in this publication; they are not a census of infrastructure in the area.</p><p>${number(x.population.missingProjectIds)} records lack an ID; ${number(x.population.repeatedIdRows)} repeat an earlier ID. An ID does not establish a unique physical asset.</p>`;}
 else if(S.field==='budget'){html=x.budgets.byCurrency.length?'<table class="inspect-table"><thead><tr><th>Currency</th><th>Published budget</th><th>Records</th></tr></thead><tbody>'+x.budgets.byCurrency.map(b=>`<tr><td>${esc(b.currency)}</td><td>${number(b.amount)}</td><td>${number(b.records)}</td></tr>`).join('')+'</tbody></table>':'<p>No numeric project budget amounts with currencies are published in these records. A total cannot be calculated.</p>';html+=`<p>${number(x.budgets.usableRecords)} of ${number(n)} records contribute. ${number(x.budgets.missingRecords)} have no usable amount and currency. Zero amounts are included.</p><p>These are published project budgets, not expenditure, contract values or verified investment. USD means the source reports US dollars. Other currencies remain separate; no exchange-rate conversion has been applied. Where several currencies are present, the prong shows the currency reported by the most records; all totals appear here. Partial totals are not the value of all projects.</p>`;}
 else if(S.field==='sectors'){html='<p>Which public needs does this publication describe?</p>'+distribution(x.sectors.values)+`<p>${number(x.sectors.unstatedRecords)} records have no sector. A record can appear in more than one sector; ${number(x.sectors.multiSectorRecords)} do so. Source labels are preserved.</p><p>These are published classifications, not a measure of need, impact or investment by sector.</p>`;}
 else if(S.field==='stages'){html='<p>The publisher reports these project stages:</p>'+distribution(x.stages.values)+`<p>${number(x.stages.unstatedRecords)} records have no stage.</p><p>A completion label does not verify that an asset was delivered, is operational or achieved its intended benefit. This is a saved publication, not a live construction update.</p>`;if(p.procurement?.completedProjectsWithActiveProcesses)html+=`<p>${number(p.procurement.completedProjectsWithActiveProcesses)} projects labelled completion also contain an active or pre-award contracting process. These are different reporting levels; check the project before interpreting its delivery status. <a href="data/procurement-evidence.json">Exact counting rule and saved source calculation</a>.</p>`;}
 else{const e=p.procurement;html=e?distribution(Object.entries(e.methods).map(([value,records])=>({value,records})).sort((a,b)=>b.records-a.records))+`<p>Counts cover ${number(e.processEntries)} recorded contracting-process entries across ${number(n)} project records. A project can contain multiple processes.</p><p>An open procedure is a published procurement method. It does not establish bidder participation, effective competition, an award, payment or successful delivery.</p><p>Methods not stated remain in the denominator. <a href="data/procurement-evidence.json">Saved source calculations</a>.</p>`:'<p>Procurement-method evidence is unavailable for this saved publication.</p>';}}
 else if(S.story==='investment'||S.story==='freshness'){({title,html}=investmentView(p));}
 else if(S.story==='records'){title='Follow a record.';html=p.excluded?'<p>No project content is redistributed for this publisher.</p>':'<p id="record-preview">Loading three titles from the saved source…</p>';}
 else {title='A portrait of published infrastructure';html=`<p>The five prongs answer different questions: projects, published budgets, infrastructure mix, reported project stage and procurement method. Each has its own unit. Connecting-line lengths do not encode values and the prongs do not form a score. The small bars show only the displayed category's share of its stated population.</p><p>This is an exploration layer. Open each prong for the calculation, missing evidence and source boundaries; the record explorer remains the detailed record layer.</p><p>There is no cross-publisher ranking or comparison. Publication scope, periods and local circumstances differ.</p><p>Map anchors identify publishers, not project locations or national coverage. Project counts refer to published IDs. Budgets remain in their published currencies; stage and procurement labels remain publisher statements.</p><p>Snapshot ${esc(S.data.snapshotId)} · analysis ${date(S.data.generatedAt)}. <a href="https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/">OC4IDS field definitions</a> · <a href="data/map/README.md">Map provenance</a>.</p>`;}
 $('detail-title').textContent=title;$('detail-content').innerHTML=html+sourceLinks();if(S.story==='records'&&!p.excluded)loadRecords(p);
}
function distribution(values){return '<table class="inspect-table"><thead><tr><th>Reported category</th><th>Records</th></tr></thead><tbody>'+values.map(v=>`<tr><td>${esc(label(v.value))}</td><td>${number(v.records)}</td></tr>`).join('')+'</tbody></table>'}
async function loadRecords(p){try{if(!S.records.has(p.id))S.records.set(p.id,fetch(S.data.recordFiles[p.id]).then(r=>{if(!r.ok)throw Error('Unavailable');return r.json()}));const rows=await S.records.get(p.id);if(S.story==='records'&&S.selected===p.id&&$('record-preview'))$('record-preview').outerHTML='<ol>'+rows.slice(0,3).map(r=>`<li><p>${esc(r.title||'Title not published')}<br><small>${esc(r.id||'Identifier not published')}</small></p></li>`).join('')+'</ol>';}catch{S.records.delete(p.id);if(S.story==='records'&&S.selected===p.id&&$('record-preview'))$('record-preview').textContent='These records could not be loaded. Open the original source below or retry Records.'}}
function world(){S.map.fitBounds([[-55,-180],[75,180]]);}
function wireDrag(){const el=$('instrument'),handle=$('move');let drag=null;
 function shift(dx,dy){const r=handle.getBoundingClientRect(),bottom=innerWidth<=720?230:180;el.dataset.x=+(el.dataset.x||0)+Math.max(8-r.left,Math.min(innerWidth-r.right-8,dx));el.dataset.y=+(el.dataset.y||0)+Math.max(76-r.top,Math.min(innerHeight-r.bottom-bottom,dy));el.style.translate=`${el.dataset.x}px ${el.dataset.y}px`;queueLens()}
 function reset(){el.style.translate='';el.dataset.x=el.dataset.y='0';queueLens(true)}
 handle.addEventListener('pointerdown',e=>{e.preventDefault();handle.setPointerCapture(e.pointerId);drag=[e.clientX,e.clientY]});handle.addEventListener('pointermove',e=>{if(drag){shift(e.clientX-drag[0],e.clientY-drag[1]);drag=[e.clientX,e.clientY]}});for(const type of ['pointerup','pointercancel','lostpointercapture'])handle.addEventListener(type,()=>{if(drag){drag=null;queueLens(true)}});
 handle.addEventListener('keydown',e=>{const delta={ArrowLeft:[-10,0],ArrowRight:[10,0],ArrowUp:[0,-10],ArrowDown:[0,10]}[e.key];if(delta){e.preventDefault();shift(...delta);queueLens(true)}if(e.key==='Home'){e.preventDefault();reset()}});$('reset').onclick=reset;window.addEventListener('resize',()=>{lensMap.invalidateSize({pan:false});reset()});
 if(q.has('lensX')&&q.has('lensY')&&Number.isFinite(+q.get('lensX'))&&Number.isFinite(+q.get('lensY'))){const h=handle.getBoundingClientRect();shift(+q.get('lensX')*innerWidth-h.left-h.width/2,+q.get('lensY')*innerHeight-h.top-h.height/2)}
}
async function boot(){try{const snap=q.get('snapshot');if(snap&&!/^[A-Za-z0-9_-]{1,100}$/.test(snap))throw Error('Invalid snapshot link.');const r=await fetch((snap?`data/generated/snapshots/${snap}.json`:'data/generated/snapshot.json')+'?view=portrait-1');if(!r.ok)throw Error('This saved snapshot is unavailable.');S.data=await r.json();if(snap&&S.data.snapshotId!==snap)throw Error('Snapshot identity mismatch.');S.pubs=S.data.publishers;if(!current())S.selected=S.pubs.find(p=>!p.excluded).id;
 const [anchors,geo]=await Promise.all([fetch('data/map/publisher-anchors.json').then(r=>r.json()),fetch('data/map/world.geojson').then(r=>r.ok?r.json():null).catch(()=>null)]);S.map=L.map('map',{inertia:false,zoomControl:false,minZoom:.5,maxZoom:7,zoomSnap:.25}).setView([12,0],innerWidth<=720?1:2);S.map.attributionControl.addAttribution('Natural Earth · public domain');L.control.zoom({position:'bottomright'}).addTo(S.map);if(geo)L.geoJSON(geo,{style:{color:'#bdc9c3',weight:.65,fillColor:'#dce4dc',fillOpacity:.7}}).addTo(S.map);else $('status').textContent='Country outlines unavailable; publisher selection remains available.';
 S.pubs.forEach(p=>{const a=anchors[p.id];if(!a)return;const m=L.marker(a,{title:p.name,alt:p.name+' publisher anchor',icon:L.divIcon({className:'publisher-icon'+(p.excluded?' metadata':''),html:'<span></span>',iconSize:[44,44],iconAnchor:[22,22]})}).addTo(S.map).bindTooltip(alias(p));m.on('click',()=>select(p.id));S.markers[p.id]=m});
 if(q.has('lat')&&q.has('lng')&&Number.isFinite(+q.get('lat'))&&Number.isFinite(+q.get('lng'))&&Math.abs(+q.get('lat'))<=80&&Math.abs(+q.get('lng'))<=180){const zoom=+q.get('zoom');S.map.setView([+q.get('lat'),+q.get('lng')],Number.isFinite(zoom)&&zoom>=.5&&zoom<=7?zoom:2,{animate:false})}
 $('publisher-select').innerHTML='<option value="" disabled>Move to a publisher</option>'+S.pubs.map(p=>`<option value="${esc(p.id)}">${esc(alias(p))}</option>`).join('');$('publisher-select').onchange=e=>select(e.target.value);for(const [id,step]of [['previous',-1],['next',1]])$(id).onclick=()=>select(S.pubs[(S.pubs.findIndex(p=>p.id===S.selected)+step+S.pubs.length)%S.pubs.length].id);
 lensMap=L.map('lens-map',{zoomControl:false,attributionControl:false,dragging:false,touchZoom:false,scrollWheelZoom:false,doubleClickZoom:false,boxZoom:false,keyboard:false,zoomAnimation:false,fadeAnimation:false,minZoom:.5,maxZoom:9,zoomSnap:.25}).setView(S.map.getCenter(),S.map.getZoom()+1);if(geo)L.geoJSON(geo,{interactive:false,style:{color:'#7d9690',weight:1,fillColor:'#cbd9ca',fillOpacity:1}}).addTo(lensMap);Object.values(S.markers).forEach(m=>L.circleMarker(m.getLatLng(),{radius:4,color:'#fff',weight:1.5,fillColor:'#D60000',fillOpacity:1,interactive:false}).addTo(lensMap));S.map.on('move zoom',()=>queueLens());S.map.on('moveend zoomend',()=>queueLens(true));
 $('methods').onclick=()=>openInspector('methods');$('dates').onclick=()=>openInspector('investment');$('records').onclick=()=>openInspector('records');$('close').onclick=()=>$('inspector').close();$('inspector').addEventListener('close',()=>{S.story='availability';S.field=null;writeUrl()});$('world').onclick=world;wireDrag();$('share').onclick=async()=>{writeUrl();try{await navigator.clipboard.writeText(location.href);$('status').textContent='Link copied with the saved snapshot and current selection.'}catch{$('status').textContent='Copy this view from the address bar.'}};render(false);if(q.has('lensX')&&q.has('lensY')){if(q.has('focusLat')&&q.has('focusLng')&&Number.isFinite(+q.get('focusLat'))&&Number.isFinite(+q.get('focusLng'))&&Math.abs(+q.get('focusLat'))<=90)panFocus([+q.get('focusLat'),+q.get('focusLng')]);refreshLens(true)}else select(S.selected);const story=q.get('story');if(story==='field'&&definitions.some(d=>d.id===q.get('field')))inspect(q.get('field'));else if(['methods','investment','freshness','records'].includes(story))openInspector(story);
 }catch(e){$('publisher-name').textContent='Evidence unavailable';$('scope').textContent=e.message;$('status').innerHTML='<a href="evidence.html">Open the evidence and source links</a>';}}
window.addEventListener('popstate',()=>location.reload());boot();
