const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const aliases={identifiers:'cost',intersection:'accountability',gaps:'accountability',record:'schedule',action:'questions'};
try{
 const response=await fetch('data/story/road-project.json');if(!response.ok)throw Error('The saved project details could not be loaded.');
 const d=await response.json(),p=d.project,v=d.provenance;
 if(!p?.id||!p.title||!Number.isFinite(p.lengthKm)||!Number.isFinite(p.budget?.amount)||!Number.isFinite(p.contractValue?.amount)||!p.plannedStart||!p.plannedEnd||!p.process?.id||!p.process.status||!p.projectStatus||!p.organizations?.publicAuthority||!p.organizations.funder||!p.organizations.supplier||!Number.isFinite(p.reportedPayments?.total)||!v?.sourceUrl||!v.fieldPaths||!Array.isArray(v.boundaries))throw Error('The saved project details are incomplete. Open the source extract below.');
 const money=n=>new Intl.NumberFormat('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
 const states={
  'case-study':{number:p.lengthKm,unit:'kilometres of planned maintenance',title:'Keep a road working.',items:p.workItems,caption:'Published scope. The road has not been independently inspected here.'},
  cost:{number:`${p.budget.currency} ${(p.budget.amount/1e6).toFixed(1)}m`,unit:'published budget, rounded',title:'One price, two places in the publication.',items:['Project budget','Contract value','Same amount, counted once'],caption:`The published payment entries total ${p.reportedPayments.currency} ${money(p.reportedPayments.total)}. This is not independently verified expenditure.`},
  accountability:{number:'Who answers?',unit:'the published organisations',title:'A buyer, a funder, a contractor.',items:['Buyer: Road Fund, Cabo Delgado','Funder: Road Fund, FP',`Contractor: ${p.organizations.supplier}`],caption:'Role labels come from this project publication.'},
  schedule:{number:`${p.plannedStart.slice(0,4)} to ${p.plannedEnd.slice(0,4)}`,unit:'published planned period',title:'Dates to follow up.',items:['Start: 1 January 2025','End: 4 March 2027','Completed work: ask for a dated update'],caption:'This interval is a plan, not a measure of progress.'},
  questions:{number:'Ask the Road Fund',unit:'Cabo Delgado delegation',title:'Connect payments to the work.',items:['What maintenance is complete?','Which payments cover it?','Where is the latest inspection?'],caption:'Suggested follow-up. No request has been sent.'}
 };
 const chapters=[...document.querySelectorAll('.chapter')];let active,scheduled=false;
 const activate=c=>{if(c.id===active)return;active=c.id;const s=states[c.id];$('.visual').dataset.stage=c.id;$('#stage-number').innerHTML=`${esc(s.number)}<span>${esc(s.unit)}</span>`;$('#stage-title').textContent=s.title;$('#stage-detail').innerHTML=s.items.map(t=>`<li>${esc(t)}</li>`).join('');$('#stage-caption').textContent='Schematic route, not mapped geography. '+s.caption;history.replaceState(null,'','#'+c.id);};
 const read=()=>{scheduled=false;if($('#question').getBoundingClientRect().bottom>innerHeight*.45){active=null;history.replaceState(null,'','#question');return}const target=matchMedia('(max-width:760px)').matches?Math.min(innerHeight-60,370):innerHeight*.5;activate(chapters.find(c=>c.getBoundingClientRect().bottom>target)||chapters.at(-1));};
 const schedule=()=>{if(!scheduled){scheduled=true;requestAnimationFrame(read)}};
 const followHash=()=>{const id=location.hash.slice(1),mapped=aliases[id];if(mapped){history.replaceState(null,'','#'+mapped);$('#'+mapped).scrollIntoView()}schedule()};
 addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);addEventListener('hashchange',followHash);
 if(location.hash){const id=aliases[location.hash.slice(1)]||location.hash.slice(1);document.getElementById(id)?.scrollIntoView()};followHash();
 for(const button of document.querySelectorAll('[data-evidence]'))button.onclick=()=>{
  $('#evidence-body').innerHTML=`<p>Mozambique's Road Fund published the information about the R762 between Mocímboa da Praia and Palma. It describes the maintenance planned, the price, the organisations involved, the dates and reported payments.</p><h3>What have we checked?</h3><p>We checked the facts and totals in this story against the published data. We have not inspected the road or independently checked the payment receipts.</p><p>The story uses the publication saved on 5 September 2026. We checked these project details on 6 September 2026.</p><h3>What would tell us more?</h3><p>A dated update from the Road Fund's Cabo Delgado delegation linking completed maintenance to payments and the latest inspection would help answer what has happened on the road.</p><details><summary>Project reference and technical source details</summary><p>Include this project reference when asking the Road Fund about the work: <code>${esc(p.id)}</code>.</p><p>Published budget: ${esc(p.budget.currency)} ${money(p.budget.amount)}. Contract value: ${esc(p.contractValue.currency)} ${money(p.contractValue.amount)}.</p><p>Reported payments: ${p.reportedPayments.count} entries, ${esc(p.reportedPayments.currency)} ${money(p.reportedPayments.total)}, latest ${esc(p.reportedPayments.lastDate)}.</p><p>The project is labelled <b>${esc(p.projectStatus)}</b>; its contracting process is labelled <b>${esc(p.process.status)}</b>. These labels describe different levels and do not establish current delivery.</p><h3>Notes on interpreting the source</h3><ul>${v.boundaries.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><p>Package SHA256: <code>${esc(d.packageSha256)}</code></p><ul>${Object.entries(v.fieldPaths).map(([k,path])=>`<li>${esc(k)}: <code>${esc(path)}</code></li>`).join('')}</ul></details>`;$('#evidence').showModal();
 };
}catch(error){$('#story-status').textContent=error.message;$('#story-status').hidden=false;document.querySelectorAll('[data-evidence]').forEach(b=>{b.disabled=true})}
