import {calculatePublisherInsights} from '../publisher-insights.mjs';
import fs from 'node:fs';import path from 'node:path';import {writeStoryData} from './story-data.mjs';
const out='dist';fs.mkdirSync(out,{recursive:true});for(const f of ['index.html','explorer.html','evidence.html','style.css','app.js','map-app.js','map-selection.mjs','glyph.mjs','exhibit.css','story.css','story.mjs','README.md'])fs.copyFileSync(f,path.join(out,f));for(const dir of ['vendor','data/map']){fs.mkdirSync(path.join(out,dir),{recursive:true});for(const f of fs.readdirSync(dir))fs.copyFileSync(path.join(dir,f),path.join(out,dir,f));}fs.writeFileSync(path.join(out,'.nojekyll'),'');
fs.copyFileSync('data/procurement-evidence.json',path.join(out,'data/procurement-evidence.json'));fs.mkdirSync(path.join(out,'data/story'),{recursive:true});fs.copyFileSync('data/story/road-project.json',path.join(out,'data/story/road-project.json'));
const procurement=JSON.parse(fs.readFileSync('data/procurement-evidence.json'));
const latest=JSON.parse(fs.readFileSync('data/generated/snapshot.json'));
writeStoryData('data/generated/snapshots/atlas-56e8378e871df657e298.json',path.join(out,'data/generated/storyboard.json'));
for(const name of fs.readdirSync('data/generated/snapshots').filter(f=>f.startsWith('atlas-')&&f.endsWith('.json'))){const s=JSON.parse(fs.readFileSync(path.join('data/generated/snapshots',name)));const recordFiles={};for(const p of s.publishers){p.insights=calculatePublisherInsights(p,s.projects);const e=procurement.snapshotId===s.snapshotId?procurement.publishers[p.id]:null;if(e){if(e.sourceSha256!==p.sha256||e.derivedSha256!==(p.derivedSha256??null)||e.records!==p.recordCount||e.processEntries!==p.processEntries||!Number.isInteger(e.completedProjectsWithActiveProcesses)||e.completedProjectsWithActiveProcesses<0||e.completedProjectsWithActiveProcesses>p.recordCount||!procurement.stageMethod||Object.values(e.methods).reduce((a,b)=>a+b,0)!==e.processEntries)throw Error('Procurement evidence does not match saved source: '+p.id);p.procurement=e;}if(p.excluded)continue;const rel=`data/generated/records/${s.snapshotId}/${p.id}.json`;fs.mkdirSync(path.dirname(path.join(out,rel)),{recursive:true});const rows=s.projects.filter(r=>r.sourceId===p.id).map(({sourceId,publisher,country,source,...r})=>r);fs.writeFileSync(path.join(out,rel),JSON.stringify(rows));recordFiles[p.id]=rel;}
const {projects,...meta}=s;const manifest={...meta,recordFiles,format:'atlas-snapshot-index-v1'};fs.mkdirSync(path.join(out,'data/generated/snapshots'),{recursive:true});const bytes=JSON.stringify(manifest);fs.writeFileSync(path.join(out,'data/generated/snapshots',name),bytes);if(s.snapshotId===latest.snapshotId)fs.writeFileSync(path.join(out,'data/generated/snapshot.json'),bytes);}
console.log('Static build complete; raw caches excluded.');
