import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import readline from 'node:readline';import {fileURLToPath} from 'node:url';import {project,counts,duplicates,dateValid} from './metrics.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),raw=process.env.ATLAS_RAW_DIR||path.join(root,'data/raw'),out=path.join(root,'data/generated');
const registry=JSON.parse(fs.readFileSync(process.env.ATLAS_REGISTRY_PATH||path.join(root,'data/registry.json')));if(!Array.isArray(registry)||!registry.length)throw Error('Invalid registry');
const observed=process.env.ATLAS_OBSERVED_AT||new Date().toISOString();if(!dateValid(observed))throw Error('Invalid observation time');
const projects=[],publishers=[];
for(const r of registry){const url=r.downloads?.find(d=>d.format==='json')?.url;if(!url)throw Error('Registry JSON download missing');const id=new URL(url).pathname.split('/').at(-1).replace(/\.json$/,'');if(!/^[a-z_0-9-]+$/.test(id))throw Error('Invalid source identifier');const s={...r,id,url};const json=path.join(raw,id+'.json'),nd=path.join(raw,id+'.ndjson');const licensed=Boolean(r.license?.url)&&(/creativecommons.org\/licenses\/by\/4\.0\/?/.test(r.license.url)||/opendatacommons.org\/licenses\/pddl\/1\.0/.test(r.license.url));
 let meta={},rows=[],sha=null,derivedSha=null;
 if(licensed){if(fs.existsSync(nd)){const mp=path.join(raw,id+'.meta.json');if(!fs.existsSync(mp))throw Error('Missing metadata for '+id);meta=JSON.parse(fs.readFileSync(mp));const hash=crypto.createHash('sha256');const stream=fs.createReadStream(nd);stream.on('data',b=>hash.update(b));for await(const line of readline.createInterface({input:stream,crlfDelay:Infinity})){if(line.trim())rows.push(project(JSON.parse(line),s,observed));}derivedSha=hash.digest('hex');sha=fs.readFileSync(path.join(raw,id+'.json.sha256'),'utf8').trim();}else{if(!fs.existsSync(json))throw Error('Licensed source unavailable: '+id);const b=fs.readFileSync(json);sha=crypto.createHash('sha256').update(b).digest('hex');const pkg=JSON.parse(b);if(!Array.isArray(pkg.projects))throw Error('No projects array: '+id);meta={...pkg};delete meta.projects;for(const p of pkg.projects)rows.push(project(p,s,observed));}if(!meta.version)throw Error('Missing package version: '+id);projects.push(...rows);}
 const c=counts(rows);publishers.push({id,name:r.publisher.name,country:r.publisher.country,sourceUrl:r.source_url,portal:r.portal,license:r.license,downloadUrl:url,loadedAt:r.loaded_at,packageVersion:meta.version||null,publishedDate:meta.publishedDate||null,extensions:meta.extensions??[],recordCount:rows.length,duplicateIds:duplicates(rows),missingIds:rows.filter(p=>!p.id).length,metricCounts:c,processProjects:c[2],processCount:rows.reduce((n,p)=>n+p.contractingProcesses,0),processEntries:rows.reduce((n,p)=>n+p.processEntries,0),invalidUpdated:rows.filter(p=>p.updated&&!dateValid(p.updated)).length,missingUpdated:rows.filter(p=>!p.updated).length,futureUpdated:rows.filter(p=>dateValid(p.updated)&&Date.parse(p.updated)>Date.parse(observed)).length,sectors:[...new Set(rows.flatMap(p=>p.sector))].sort(),statuses:[...new Set(rows.map(p=>p.status))].sort(),sha256:sha,derivedSha256:derivedSha,available:licensed,excluded:licensed?null:'No stated reuse licence in the registry; project content excluded.'});
}
const metricVersion='1.0.0',fingerprint=crypto.createHash('sha256').update(JSON.stringify({registry,publishers:publishers.map(p=>[p.id,p.sha256,p.derivedSha256]),metricVersion,observed})).digest('hex').slice(0,20),snapshotId='atlas-'+fingerprint;
const c=counts(projects),snapshot={snapshotId,generatedAt:observed,metricVersion,registryUrl:'https://api.datastore.infrastructuretransparency.org/datasets',publishers,projects,metricCounts:c,findings:{licensedPublishers:publishers.filter(p=>!p.excluded).length,licensedProjects:projects.length,titleCoverage:c[0]/projects.length,processCoverage:c[2]/projects.length,budgetCurrencyCoverage:c[1]/projects.length}};
fs.mkdirSync(path.join(out,'snapshots'),{recursive:true});const bytes=JSON.stringify(snapshot);if(Buffer.byteLength(bytes)>60_000_000)throw Error('Snapshot exceeds bounded60MB output');const archive=path.join(out,'snapshots',snapshotId+'.json');if(fs.existsSync(archive)){if(fs.readFileSync(archive,'utf8')!==bytes)throw Error('Snapshot identity collision');}else fs.writeFileSync(archive,bytes,{flag:'wx'});const tmp=path.join(out,`snapshot.tmp-${process.pid}`);fs.writeFileSync(tmp,bytes);fs.renameSync(tmp,path.join(out,'snapshot.json'));console.log(JSON.stringify({snapshotId,records:projects.length,publishers:publishers.length,metricCounts:c,bytes:Buffer.byteLength(bytes)}));
